Vivart/Vivart/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vivart.DbContextData;
using Vivart.Models;

namespace Vivart.Controllers
{
    public class SliderController : Controller
    {
        // GET: Slider
        public ActionResult Index()
        {
            using (VivartContext db = new VivartContext())
            {
                return View(db.Gallery.ToList());
            }
        }

        //Add images in slider
        public ActionResult AddImage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddImage(HttpPostedFileBase ImagePath)
        {
            if(ImagePath != null)
            {
                string pic = System.IO.Path.GetFileName(ImagePath.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/images/"), pic);
                ImagePath.SaveAs(path);
                using (VivartContext db = new VivartContext())
                {
                    Gallery gallery = new Gallery { ImagePath = "~/Content/images/" + pic };
                    db.Gallery.Add(gallery);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }


        // Delete Multiple Images
        public ActionResult DeleteImages()
        {
            using (VivartContext db = new VivartContext())
            {
                return View(db.Gallery.ToList());
            }
        }

        [HttpPost]
        public ActionResult DeleteImages(IEnumerable<int> ImagesIds)
        {
            using (VivartContext db = new VivartContext())
            {
                foreach (var id in ImagesIds)
                {
                    var image = db.Gallery.Single(s => s.Id == id);
                    string imgPath = Server.MapPath(image.ImagePath);
                    db.Gallery.Remove(image);
                    if (System.IO.File.Exists(imgPath))
                        System.IO.File.Delete(imgPath);
                }
                db.SaveChanges();
            }
            return RedirectToAction("DeleteImages");
        }



    }
}

Vivart/Vivart/Views/Slider/AddImage.cshtml
@model Vivart.Models.Gallery
@{
    ViewBag.Title = "AddImage";
}

<h2>AddImage</h2>

                        <!--method controller-->
@using (Html.BeginForm("AddImage", "Slider", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Gallery</legend>

        <div class="editor-label">
            Upload Image
        </div>
        <div class="editor-field">
            <input type="file" id="ImagePath" name="ImagePath" />
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
    <p>@Html.ActionLink("Slider Home", "Index", "Slider")</p>
}

Vivart/Vivart/Views/Slider/DeleteImages.cshtml
@{
    ViewBag.Title = "DeleteImages";
}

<h2>DeleteImages</h2>
@using (Html.BeginForm("DeleteImages", "Slider", FormMethod.Post))
{
    <table style="background-color:azure" border="1">
        <thead style="background-color:gray">
            <tr>
                <th>Select</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            @Html.EditorForModel()
        </tbody>
    </table>
    <input type="submit" value="Delete Selected Images" />
}
<p>@Html.ActionLink("Slider Home", "Index", "Slider")</p>

Vivart/Vivart/Views/Slider/Index.cshtml
@model IEnumerable<Vivart.Models.Gallery>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    <!-- text methodname controller-->
    @Html.ActionLink("Add Image", "AddImage", "Slider", new { id = "linkAddimage" }, null) |
    @Html.ActionLink("Delete Image", "DeleteImages", "Slider", new { id = "linkDeleteImage" }, null)
</p>
@Html.Partial("~/Views/Shared/SliderPartial.cshtml", Model)